backup_mariadb: encrypt first

diff --git a/scripts/transmit/backup_mariadb b/scripts/transmit/backup_mariadb
--- a/scripts/transmit/backup_mariadb
+++ b/scripts/transmit/backup_mariadb
@@ -4,7 +4,7 @@ config="/fs/storage/share/operations/secrets/.sibis/.sibis-general-config.yml"
 backup_src=/fs/storage/mariadb-redcap-archive
 backup_lock=/fs/storage/ncanda_redcap_backup.lock
 retain_local_copy=${1:-1}
-backup_src_spec="${backup_src}/*.sql.gz"
+backup_src_spec="${backup_src}/redcap_mariadb_backup-*.sql.gz"
 
 ## Load common utils
 source $cur_dir/transmit_utils
@@ -23,10 +23,21 @@ function remove_lock() {
 
 trap "remove_lock" EXIT
 
+# get most recent archive
 archive_file=$(ls -t ${backup_src_spec} | head -n 1)
-if [[ -z "$archive_file" ]]; then
-  printf 'ERROR: Backup date could not be determined. Date not detected in %s' "$date_file"
+archive_file_aes="${archive_file}.aes"
+
+if [[ -z "${archive_file}" ]]; then
+  printf 'ERROR: No recent archives found' 
   exit 1
 fi
 
-upload_to_s3 $archive_file ${retain_local_copy}
+if [ -f "${archive_file_aes}" ]; then
+  printf 'INFO: latest archive already has encrypted version. It should have been backed up already. Retrying.'
+else
+  set -e
+  aespipe -P ${HOME}/aes/keys -e aes256 < "${archive_file}" > "${archive_file_aes}"
+  set +e
+fi
+
+upload_to_s3 $archive_file ${retain_local_copy} && rm "${archive_file}"
