backup_mariadb: support additional file specs; file rotation support

diff --git a/scripts/transmit/backup_mariadb b/scripts/transmit/backup_mariadb
--- a/scripts/transmit/backup_mariadb
+++ b/scripts/transmit/backup_mariadb
@@ -4,12 +4,14 @@ config="/fs/storage/share/operations/secrets/.sibis/.sibis-general-config.yml"
 backup_src=/fs/storage/mariadb-redcap-archive
 backup_lock=/fs/storage/ncanda_redcap_backup.lock
 retain_local_copy=${1:-1}
-backup_file_glob="redcap_mariadb_backup-*.sql.gz"
-fq_backup_src_spec="${backup_src}/${backup_file_glob}"
+backup_db_file_glob="redcap_mariadb_backup-*.sql.gz"
+backup_event_table_file_glob="redcap_log_event-export-*.csv.gz"
+backup_view_table_file_glob="redcap_log_view-export-*.csv.gz"
 mariadb_subdir=redcap-mariadb
 aes_extension=".aes"
-aes_backup_file_glob="${backup_file_glob}${aes_extension}"
+#aes_backup_file_glob="${backup_db_file_glob}${aes_extension}"
 s3_backups_to_retain=10
+local_backups_to_retain=10
 
 ## Load common utils
 source $cur_dir/transmit_utils
@@ -28,24 +30,54 @@ function remove_lock() {
 
 trap "remove_lock" EXIT
 
-# get most recent archive
-archive_file=$(ls -t ${fq_backup_src_spec} 2> /dev/null | head -n 1)
-archive_file_aes="${archive_file}${aes_extension}"
 
-if [[ -z "${archive_file}" ]]; then
-  printf 'ERROR: No recent archives found\n' 
-  exit 1
-fi
+TRAP_DELETE=
+function trap_delete_incomplete() {
+  if [[ -n "${TRAP_DELETE}" ]]; then
+    echo Deleting incomplete file: ${TRAP_DELETE}
+    rm ${TRAP_DELETE}
+  fi
+}
+trap trap_delete_incomplete INT
 
-if [ -f "${archive_file_aes}" ]; then
-  printf 'INFO: latest archive already has encrypted version. It should have been backed up already. Retrying.\n'
-else
+
+function backup_and_rotate() {
+
+  fq_spec=$1
+  fq_aes_spec=${fq_spec}${aes_extension}
+  aes_glob=`basename ${fq_aes_spec}` 
+
+  # get most recent archive
+  archive_file=$(ls -t ${fq_spec} 2> /dev/null | grep -v "\-latest" | head -n 1)
+  archive_file_aes="${archive_file}${aes_extension}"
+
+  if [[ -z "${archive_file}" ]]; then
+    printf 'ERROR: No recent archives found\n' 
+    exit 1
+  fi
+
+  if [ -f "${archive_file_aes}" ]; then
+    printf "INFO: Latest archive already has encrypted version: ${archive_file_aes}\n"
+    printf 'INFO: It should have been backed up already. Retrying.\n'
+  else
+    TRAP_DELETE="${archive_file_aes}"
+    printf "INFO: encrypting archive before upload: ${archive_file_aes}\n"
+    aespipe -P ${HOME}/aes/keys -e aes256 < "${archive_file}" > "${archive_file_aes}"
+    if [ $? -ne 0 ]; then
+      trap_delete_incomplete
+      exit 1
+    fi
+    TRAP_DELETE=
+  fi
+
   set -e
-  printf 'INFO: encrypting archive before upload.\n'
-  aespipe -P ${HOME}/aes/keys -e aes256 < "${archive_file}" > "${archive_file_aes}"
+  upload_to_s3_subdir $archive_file_aes ${retain_local_copy} ${mariadb_subdir} 
   set +e
-fi
+  # s3://ncanda/db/redcap-mariadb/redcap*.aes
+  delete_oldest_files_s3 ${mariadb_subdir} ${aes_glob} ${s3_backups_to_retain}
+  delete_oldest_files ${fq_aes_spec} ${local_backups_to_retain}
+}
 
-upload_to_s3_subdir $archive_file_aes ${retain_local_copy} ${mariadb_subdir} && rm "${archive_file}"
-# s3://ncanda/db/redcap-mariadb/redcap*.aes
-delete_oldest_files ${mariadb_subdir} ${aes_backup_file_glob} ${s3_backups_to_retain}
+backup_and_rotate ${backup_src}/${backup_db_file_glob}
+backup_and_rotate ${backup_src}/${backup_event_table_file_glob}
+backup_and_rotate ${backup_src}/${backup_view_table_file_glob}
